<template>
    <div class="landing p-grid">
        <div class="p-col-12">
            <img alt="EcoHero logo" class="responsive" src="../media/img/logowhite.png">
        </div>
        <div class="card p-col-12 p-md-12 p-lg-6 center">
            <Divider align="center">
                <div class="p-d-inline-flex p-ai-center">
                    <em class="pi pi-home p-mr-2"></em>
                    <strong>Welcome to EcoHero</strong>
                </div>
            </Divider>
            <p>
                EcoHero is a platform to challenge people to be more sustainable. Being sustainable is quite hard, which is why
                this platform has a reward system. You will get points by entering sustainable activities, challenge your friends and
                become a EcoHero. Sign up and make the world a better place.
            </p>

            <Divider align="center" class="p-col-fixed center" style="width:150px">
                <Button label="Button" @click="handleClickSignIn()" icon="pi pi-google" class="p-button-outlined" id="join-button">Join us</Button>
            </Divider>

            <div>
                <Divider align="center">
                    <div class="p-d-inline-flex p-ai-center">
                        <em class="pi pi-user p-mr-2"></em>
                        <strong>Cookies</strong>
                    </div>
                </Divider>
                <p>
                    We value your privacy! This means we only collect essential cookies.
                    These cookies are needed to move around and interact with the website. 
                    Without these cookies the website and it's services cannot be provided.
                </p>
                <img src="../media/cookie.png"
                     style="width: 20%;margin-top: 20px; border-radius:50%;" alt="cookies" />
            </div>
        </div>     
    </div>
</template>

<script>
    import { inject, toRefs } from "vue";

    export default {
        name: 'Landing',
        data() {
            return {
                id: 0
            }
        },
        methods: {
            async handleClickSignIn() {
                try {
                    const googleUser = await this.$gAuth.signIn();
                    this.id = googleUser.getId();
                    if (!googleUser) {
                        return null;
                    }

                    // send the token from google to the backend
                    await this.sendtoken();

                } catch (error) {
                    //on fail do something
                    console.error(error);
                    return null;
                }
            },
            async sendtoken() {
                // retreive the google token from the client
                let token = this.$gAuth.instance.currentUser.get().getAuthResponse().id_token;
                const response = await fetch("api/accounts/auth/google", {
                    method: "POST",
                    headers: {
                        "Content-type": "application/json; charset=UTF-8",
                        "Accept": "application/json"
                    },
                    body: JSON.stringify({
                        IdToken: token
                    })
                });

                const jwttoken = await response.json();
                this.$store.dispatch('saveJwtToken', jwttoken.token);
                this.getUser(jwttoken.token);
            },
            getUser(token) {
                // Send the bearer token that is generated by us in the header, to verify if the user is autorised 
                const headers = {
                    'Authorization': 'Bearer ' + token,
                    'Content-Type': 'application/json',
                    "Accept": "application/json"
                };
                fetch("api/user/id=" + this.id, { headers })
                    .then(response => response.json())
                    .then(data => {
                        this.$store.dispatch('saveCurrentUser', data)
                        this.getRole(token, data.role);
                    });
            },
            getRole(token, id) {
                // Send the bearer token that is generated by us in the header, to verify if the user is autorised
                const headers = {
                    'Authorization': 'Bearer ' + token,
                    'Content-Type': 'application/json',
                    "Accept": "application/json"
                };
                fetch("/api/rol/id=" + id, { headers })
                    .then(response => response.json())
                    // Send current role to the store
                    .then(data => (this.$store.dispatch('saveCurrentRole', data.name)))
                    .then(setTimeout(() => this.$router.push('/'), 100));
            }
        },
        setup(props) {
          
        }
    }
</script>

<style scoped>
    .center {
        margin: auto;
        padding: 10px;
    }
    .responsive {
        width: 100%;
        max-width: 400px;
        height: auto;
        margin-bottom: -5%;
    }
</style>
